config/routes.rb
JimmyMeAr::Application.routes.draw do
  root :to => 'blogs#index', :as => :root

  resources :blogs, :except => :show
  match 'blogs/:slug' => 'blogs#show', :as => :blog, :via => :get
  match 'tags/:tag' => 'blogs#find_all_by_tag', :as => :tag, :via => :get
  match 'sign_in' => 'auth#sign_in', :as => :sign_in, :via => [:get, :post]
  match 'sign_out' => 'auth#sign_out', :as => :sign_out  
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/blog.rb
# coding: utf-8
class Blog < ActiveRecord::Base

  validates_presence_of :title, :content
  validates_length_of :title, :minimum => 2, :maximum => 50
  validates_length_of :content, :minimum => 2, :maximum => 10000
  validates_uniqueness_of :title  

  attr_accessible :title, :content, :slug, :tags

  def tag_list=(value)
    if !value.blank?
      self.tags = value.gsub(/\s/, '').split(/,|，/).join(",")
    end
  end

  def tag_list
    self.tags.split(",")
  end

  TRUNCATE = 600

  def summary
    self.content.truncate(TRUNCATE, :truncate_string => '...')
  end

  def whole_content?
    self.content == self.summary
  end

  before_save do
    if self.slug.blank?
      self.slug = Pinyin.t(self.title, '-')
    else
      errors[:slug] = "Slug is alreay token." if Blog.exists?(:slug => self.slug)
    end
  end  
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :signed_in?
  
  def signed_in?
    session[:admin_user] == 'Jimmy'
  end
  
  def require_login
    unless signed_in?
      clear_login_state
      flash[:error] = '请登录后访问'
      redirect_to sign_in_path
    end
  end

  def clear_login_state
    session[:admin_user] = nil
    session.clear
  end

  def set_seo_meta(title = nil, meta_keywords = nil, meta_description = nil)
    default_keywords = %Q(Jimmy's Blog Ruby on Rails, Ruby, Rails, Jimmy)
    default_description = %Q(Jimmy's Blog Ruby on Rails, Ruby, Rails, Jimmy)
    @page_title = title || "Jimmy's Blog"    
    @keywords = meta_keywords || default_keywords
    @description = meta_description || default_description
  end   
    
end

app/controllers/auth_controller.rb
# coding: utf-8
class AuthController < ApplicationController
  before_filter :check_signed_in, :only => :sign_in
  before_filter :require_login, :only => :sign_out

  def sign_in
    if request.post?
      if params[:email] == Setting.admin_email && params[:password] == Setting.admin_pwd
        session[:admin_user] = "Jimmy"
      else
        flash[:error] = '邮箱或者密码不正确'
      end
      redirect_to :back
    end
    set_seo_meta('登录')    
  end

  def sign_out
    clear_login_state
    redirect_to root_path    
  end

  private

  def check_signed_in
    redirect_to :root if signed_in?
    return
  end  
end

app/controllers/blogs_controller.rb
# coding: utf-8
class BlogsController < ApplicationController
  before_filter :require_login, :except => [:show, :index, :find_all_by_tag]

  def index
    @blogs = Blog.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    set_seo_meta
  end

  def show
    @blog = Blog.find_by_slug(params[:slug])
    set_seo_meta(@blog.title, nil, nil)
  end

  def new
    @blog = Blog.new
    set_seo_meta
  end

  def create
    blog = Blog.create(params[:blog])
    flash[:error] = blog.errors.full_messages
    redirect_to :back
  end

  def edit
    @blog = Blog.find_by_id(params[:id])
    set_seo_meta
  end

  def update
    blog = Blog.find_by_id(params[:id])
    if blog.update_attributes(params[:blog])
      redirect_to blog_path(blog.slug)
    else
      flash[:error] = blog.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    blog = Blog.find_by_id(params[:id])
    blog.destroy
    redirect_to blogs_path
  end

  def find_all_by_tag
    @blogs = Blog.where("tags LIKE '%#{params[:tag]}%'").order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    set_seo_meta
    render :action => :index
  end

end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper

  def markdown(text)
    options = {   
      :autolink => true, 
      :space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :hard_wrap => true,
      :strikethrough =>true
    }
    markdown = Redcarpet::Markdown.new(HTMLwithAlbino, options)
    markdown.render(h(text)).html_safe
  end

  class HTMLwithAlbino < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, :lexer => language, :formatter => 'html', :options => {:encoding => 'utf-8'})
    end
  end  

end

app/views/blogs/edit.html.slim
.blogs
  .new_post
    = form_for @blog do |f|
      p= f.text_field :title, :class => 'normal', :placeholder => '标题'
      p= f.text_field :slug, :class => 'normal', :placeholder => 'Slug'
      p= f.text_area :content, :class => 'normal', :size => '120x30', :placeholder => '正文，支持Markdown'
      p= f.text_field :tags, :class => 'normal', :placeholder => '标签，用，隔开'
      p= f.submit '确定'

app/views/blogs/index.html.slim
.blogs
  - @blogs.each do |blog|
    .post.clearfix
      .post_title
        a href=blog_path(blog.slug) = blog.title

      .post_body= markdown(blog.summary)
      - unless blog.whole_content?
        .read_on 
          p 
            a href="#{blog_path(blog.slug)}" +++ 阅读全文 +++

      .post_summary
        ul.clearfix
          li.posted_at= blog.created_at.strftime("%F %T")
          - blog.tag_list.each do |tag|
            li 
              a href="#{tag_path(tag)}"= tag
              
  .pagination_panel
    = will_paginate(@blogs, :class => 'digg_pagination')              

app/views/blogs/new.html.slim
.blogs
  .new_post
    = form_for @blog do |f|
      p= f.text_field :title, :class => 'normal', :placeholder => '标题'
      p= f.text_field :slug, :class => 'normal', :placeholder => 'Slug, 不填的话自动生成'
      p= f.text_area :content, :class => 'normal', :size => '120x30', :placeholder => '正文，支持Markdown'
      p= f.text_field :tags, :class => 'normal', :placeholder => '标签，用，隔开'
      p= f.submit '确定'

app/views/blogs/show.html.slim
.blogs
  .post.clearfix
    .post_title
      a href="#{blog_path(@blog.slug)}"
        = @blog.title

    .post_body= markdown(@blog.content)

    .post_summary
      ul.clearfix
        li.posted_at= @blog.created_at.strftime("%F %T")
        - @blog.tag_list.each do |tag|
          li 
            a href="#{tag_path(tag)}"= tag
        - if signed_in?
          li.yellow
            a href="#{edit_blog_path(@blog)}" 编辑
          li.red
            a href="#{blog_path(@blog)}" data-confirm="确定删除吗？" data-method="DELETE" 删除

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    = stylesheet_link_tag 'app', 'blog'
    = javascript_include_tag 'app'
    meta charset='utf-8'
    mata name='keywords' content="#{@keywords}"
    meta name='description' content="#{@description}"
    title= @page_title
    = csrf_meta_tags   
  body
    .main-container
      .header-container.clearfix
        .nav.clearfix
          ul
            li
              a href="#{root_path}"= "Jimmy's Blog"
            - if signed_in?
              li
                a href="#{new_blog_path}" New Post              
              li
                a href="#{sign_out_path}" Sign out            
      .blog-container
        = render 'shared/flash_notice'
        = yield

app/views/shared/_flash_notice.html.slim
- unless flash[:error].blank?
  - errors = Array flash[:error]
  .flash_notice.error
    p
      = "以下 #{errors.size} 处错误导致不能提交："
    .messages
      ul
        - errors.each do |err|
          li= err

- unless flash[:success].blank?
  - notices = Array flash[:success]
  .flash_notice.success
    .messages
      ul
        - notices.each do |n|
          li= n